name: Docker Publish Action
description: Build and publish Docker images to Docker Hub
author: Sriman

branding:
  icon: cpu
  color: gray-dark

inputs:
  context_path:
    description: Build context path
    required: false
    default: "."

  docker_username:
    description: Docker Hub username
    required: true

  docker_password:
    description: Docker Hub password or token
    required: true

  dockerfile_path:
    description: Path to the Dockerfile
    required: false
    default: "./Dockerfile"

  image_repo:
    description: Repository for the Docker image (e.g. username/repo)
    required: true

  version:
    description: Application version (e.g. 1.2.3, 1.2.3-beta.2, 1.2.3-34)
    required: true

runs:
  using: composite
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Parse version
      id: version
      shell: bash
      run: |
        set -e

        RAW_VERSION="${{ inputs.version }}"
        VERSION="${RAW_VERSION#v}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

        if [[ "$VERSION" == *"-"* ]]; then
          PRERELEASE="${VERSION#*-}"
          echo "prerelease=true" >> $GITHUB_OUTPUT

          if [[ "$PRERELEASE" =~ ^[0-9]+$ ]]; then
            echo "kind=numeric" >> $GITHUB_OUTPUT
          else
            LABEL="${PRERELEASE%%.*}"
            echo "kind=labeled" >> $GITHUB_OUTPUT
            echo "label=$LABEL" >> $GITHUB_OUTPUT
          fi
        else
          echo "prerelease=false" >> $GITHUB_OUTPUT
          echo "kind=stable" >> $GITHUB_OUTPUT
          echo "major=${VERSION%%.*}" >> $GITHUB_OUTPUT
        fi

    - name: Generate Docker tags
      id: docker_tags
      shell: bash
      run: |
        set -e

        IMAGE="${{ inputs.image_repo }}"
        VERSION="${{ steps.version.outputs.version }}"
        KIND="${{ steps.version.outputs.kind }}"

        echo "$IMAGE:$VERSION" > tags.txt

        if [[ "$KIND" == "stable" ]]; then
          echo "$IMAGE:latest" >> tags.txt
          echo "$IMAGE:${{ steps.version.outputs.major }}" >> tags.txt

        elif [[ "$KIND" == "numeric" ]]; then
          echo "$IMAGE:next" >> tags.txt

        elif [[ "$KIND" == "labeled" ]]; then
          echo "$IMAGE:${{ steps.version.outputs.label }}" >> tags.txt
        fi

        echo "Generated Docker tags:"
        cat tags.txt

        echo "tags<<EOF" >> $GITHUB_OUTPUT
        cat tags.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context_path }}
        file: ${{ inputs.dockerfile_path }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.docker_tags.outputs.tags }}
